In [2]:
!pip install opencv_python

In [2]:
import cv2

img = cv2.imread("face.jpg")
#print(type(img)) #<class 'numpy type'>

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) # 將圖片轉為灰階, 灰階節省演算效能


-1

In [20]:
# 分類器模型 - 串聯分類器物件:切割範圍，演算是否有眼睛、臉的弧線等條件判斷

faceCascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")
#faceCascade = cv2.CascadeClassifier(r'C:\Users\User\anaconda3\Lib\site-packages\cv2\data\haarcascade_frontalface_default.xml')

# 偵測複數人臉範圍，得到為臉的範圍 list
faces = faceCascade.detectMultiScale(
    gray,
    scaleFactor=1.12,
    minNeighbors=3,
    minSize=(5,5)
)

print(faces)
'''
for face in faces:
    print(face[0])
    break
    
for (x,y,w,h) in faces:
    print(x,y,w,h)
    break
'''

# 畫製人臉方框
i = 0
for (x,y,w,h) in faces:   
    if i % 2 == 0:
        cv2.rectangle(img, (x,y), (x+w, y+h), (0,255,0), 3)
    else:
        cv2.rectangle(img, (x,y), (x+w, y+w), (0,0,255), 3)
    i += 1

cv2.imshow("test", img)
cv2.waitKey()


[[136 560  31  31]
 [658 433  55  55]
 [527 295  61  61]
 [ 56 343  65  65]
 [184 304  60  60]
 [771 353  72  72]
 [307 307  59  59]
 [384 349  56  56]
 [493 365  65  65]
 [233 369  65  65]
 [611 315  68  68]
 [466 253  73  73]]


-1

In [ ]:
# imshow(title, img obj) 不要直接執行
cv2.imshow("test", gray)

cv2.waitKey() #暫停一下讓人與視窗互動的時間，不填時間就是等人關閉視窗

In [3]:
print(cv2.__file__)

C:\Users\User\anaconda3\Lib\site-packages\cv2\__init__.py
