In [7]:
# 4大天王人臉辨識

import cv2
import numpy as np # list to array

img_material = []
nameList = ["L", "M", "Q", "Z"]
nameListIdx = 0
labels = []

for name in nameList:
    num = 0
    while num < 10:
        num += 1
        imgName = name + str(num) + ".JPG"
        img_material.append(cv2.imread(imgName, cv2.IMREAD_GRAYSCALE))
        labels.append(nameListIdx)
    nameListIdx += 1
    
    
print(len(img_material))
print(labels)

rec = cv2.face.LBPHFaceRecognizer_create()
rec.train(img_material, np.array(labels)) 

40
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]


In [18]:
img = cv2.imread("4kings.JPG")

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

faceCascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

# 偵測複數人臉範圍，得到為臉的範圍 list
faces = faceCascade.detectMultiScale(
    gray,
    scaleFactor=1.3,
    minNeighbors=4,
    minSize=(32,32)
)

print(faces)


# 畫製人臉方框
i = 0
cut_list = []
for (x,y,w,h) in faces:
    cut_img = img[y:y+h, x:x+w] # 先 y 再 x
    cv2.imwrite("cut_"+str(i)+".jpg", cut_img)
    cut_list.append("cut_"+str(i)+".jpg")
    i += 1
    
    #v2.rectangle(img, (x,y), (x+w, y+h), (0,255,0), 2)
    #v2.putText(img, str(i), (x, y), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 255), 1, cv2.LINE_AA)
print(cut_list)

[[640  95 169 169]
 [ 51  87 182 182]
 [330  86 173 173]
 [936  94 169 169]]
['cut_0.jpg', 'cut_1.jpg', 'cut_2.jpg', 'cut_3.jpg']


In [22]:
predict_img = cv2.imread('cut_2.jpg', cv2.IMREAD_GRAYSCALE) # 測試考題
label, confidence = rec.predict(predict_img)
print("ans idx:",label,"confidence:", confidence)

ans idx: 3 confidence: 69.52989649816514


In [26]:
predict_result = []
king_list = ["Andy劉","Min黎","Aaron郭","Jacky張"]
for cut in cut_list:
    predict_img = cv2.imread(cut, cv2.IMREAD_GRAYSCALE) # 測試考題
    label, confidence = rec.predict(predict_img)
    predict_result.append(king_list[label])
    
    print("ans idx:",label,"confidence:", confidence)
    print(cut, " is ", king_list[label])

ans idx: 3 confidence: 75.06574110439642
cut_0.jpg  is  Jacky張
ans idx: 3 confidence: 63.18910429715401
cut_1.jpg  is  Jacky張
ans idx: 3 confidence: 69.52989649816514
cut_2.jpg  is  Jacky張
ans idx: 2 confidence: 67.9133030291186
cut_3.jpg  is  Aaron郭


In [28]:
ii = 0
for (x,y,w,h) in faces:
    cv2.rectangle(img, (x,y), (x+w, y+h), (0,255,0), 2)
    cv2.putText(img, predict_result[ii], (x, y), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 255), 1, cv2.LINE_AA)
    ii += 1

cv2.imshow("matchResult", img)
cv2.waitKey()

-1

In [36]:
# openCV 使用中文字型 
# https://cloud.tencent.com/developer/article/1794474
import cv2
import numpy as np
from PIL import ImageFont, ImageDraw, Image    # 載入 PIL 相關函式庫

def cv2ImgAddText(img, text, left, top, textColor=(0, 255, 0), textSize=20):

    if (isinstance(img, np.ndarray)):  #判断是否OpenCV图片类型

        img = Image.fromarray(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))

    draw = ImageDraw.Draw(img)

    fontText = ImageFont.truetype("font/simsun.ttc", textSize, encoding="utf-8")

    draw.text((left, top), text, textColor, font=fontText)

    return cv2.cvtColor(np.asarray(img), cv2.COLOR_RGB2BGR)

imgTest = cv2ImgAddText(img, "大家好", 140, 60, (255, 255, 0), 20)
cv2.imshow('chinese_test', imgTest)
cv2.waitKey(0)


-1

In [8]:
predict_img = cv2.imread('4kings.JPG', cv2.IMREAD_GRAYSCALE) # 測試考題

label, confidence = rec.predict(predict_img)

print("ans idx:",label)
print("confidence:", confidence)

ans idx: 3
confidence: 52.307229417498775
